# dlq-admin/src/main/resources/META-INF/microprofile-config.properties
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.ordersDlqIn.connector=smallrye-kafka
mp.messaging.incoming.ordersDlqIn.topic=orders.dlq
mp.messaging.incoming.ordersDlqIn.group.id=dlq-admin-group
mp.messaging.incoming.ordersDlqIn.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.ordersDlqIn.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.ordersDlqIn.failure-strategy=ignore