# api-service/src/main/resources/META-INF/microprofile-config.properties
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.ordersCreated.connector=smallrye-kafka
mp.messaging.outgoing.ordersCreated.topic=orders.created
mp.messaging.outgoing.ordersCreated.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.ordersCreated.value.serializer=org.apache.kafka.common.serialization.StringSerializer